name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Build and Test (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2

      # Linux dependencies
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libx11-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxi-dev \
          libasound2-dev \
          libgl1-mesa-dev \
          libwayland-dev \
          libxkbcommon-dev

      # Windows dependencies (if any needed)
      # - name: Install Windows dependencies
      #   if: runner.os == 'Windows'
      #   run: |
      #     choco install -y <packages>
      #   shell: pwsh

      - run: zig build
