name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Install X11 dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxcursor-dev libxinerama-dev libxrandr-dev
      - run: zig build
